### ISSUE TITLE
Theme not applying correctly

### ISSUE THREAD

**Issue by EvHackerLol** [felixhahnweilheim/humhub-themes-orange#17]
Hello,
I've uploaded theme to /theme directory of humhub. After applying this theme my humhub looks like this:

![image](https://user-images.githubusercontent.com/90171014/225534856-1479cfb2-8e19-4e5c-827d-2d2fff5e0e1d.png)

**Comment by felixhahnweilheim** [comment]
Thanks for the issue. But this theme is a module (embedded theme). Please upload it to protected/modules, not to /themes, and activate it in the Modules Administration.

**Comment by EvHackerLol** [comment]
Thank you. Now theme works correctly. :)
